global:
  dbRootPassword: "rootpasswd"
  dbUser: "mmuser"
  dbPassword: "passwd"
  dbName: "mattermost"
  mattermostLicense: "THIS STRING SHOULD BE REPLACED WITH THE CONTENTS OF YOUR LICENSE FILE"
  features:
    elasticsearch: true

tags:
  core: true
  metrics: true
  loadtest: false

mattermost-app:
  replicaCount: 2
  image:
    tag: daily-build
  
mattermost-proxy:
  replicaCount: 2

mattermost-elasticsearch:
  client:
    replicaCount: 2
  master:
    replicaCount: 3
  data:
    replicaCount: 2

mattermost-loadtest:
  numTeams: 1
  numChannelsPerTeam: 4000
  numUsers: 5000
  testLengthMinutes: 20
  numActiveEntities: 5000
  actionRateMilliseconds: 60000
  actionRateMaxVarianceMilliseconds: 15000
  pprofDelayMinutes: 15
  pprofLengthSeconds: 240
  sendReportToMMServer: false
  resultsServerUrl: ""
  resultsChannelId: ""
  resultsUsername: ""
  resultsPassword: ""

